apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kuyfw8g7m-java-quarkus
  janus-idp.io/tekton: kuyfw8g7m-java-quarkus
  backstage.io/kubernetes-id: kuyfw8g7m-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kuyfw8g7m-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
